/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Core Applications
 */
#define CONFIG_USER_INIT_INIT 1
#undef  CONFIG_USER_INIT_CONSOLE_SH
#undef  CONFIG_USER_INIT_RUN_FIREWALL
#undef  CONFIG_USER_INIT_EXPAND
#define CONFIG_USER_LOGIN_LOGIN 1
#define CONFIG_USER_CLI 1
#define CONFIG_USER_MENU_CLI 1
#undef  CONFIG_USER_CMD_CLI
#undef  CONFIG_USER_LOGIN_PASSWD
#undef  CONFIG_LIB_LIBPCAP_FORCE
#undef  CONFIG_LIB_LIBMD5_FORCE
#undef  CONFIG_LIB_NCURSES
#undef  CONFIG_LIB_CURL
#undef  CONFIG_LIB_ZLIB

/*
 * Library Configuration
 */
#define CONFIG_LIB_UC_LIBC_TIMEZONE 1
#undef  CONFIG_LIB_UC_LIBC_TZ_FROM_FILE

/*
 * Filesystem Applications
 */
#undef  CONFIG_USER_FLATFSD_XXX

/*
 * Network Applications
 */
#define CONFIG_USER_ROUTE_ARP 1
#undef  CONFIG_USER_AUTO_PROVISIONING
#undef  CONFIG_LIB_LIBSIG
#undef  CONFIG_SSLLIB
#define CONFIG_USER_BOA_SRC_BOA 1
#define CONFIG_DEFAULT_WEB 1
#define CONFIG_USER_BR2684CTL_BR2684CTL 1
#define CONFIG_USER_BRCTL_BRCTL 1
#undef  CONFIG_USER_CWMP_TR069
#define CONFIG_USER_DDNS 1
#define CONFIG_USER_DHCP_ISC_RELAY_DHCRELAY 1
#define CONFIG_USER_DNSMASQ_DNSMASQ 1
#define CONFIG_USER_SSH_DROPBEAR 1
#undef  CONFIG_USER_FTP_FTP_FTP
#undef  CONFIG_USER_FTPD_FTPD
#undef  CONFIG_USER_FREESWAN
#undef  CONFIG_USER_IDB_IDB
#undef  CONFIG_USER_ROUTE_IFCONFIG
#undef  CONFIG_USER_IFMOND2_IFMOND
#define CONFIG_USER_IGMPPROXY 1

/*
 * SAMBA
 */
#undef  CONFIG_USER_SAMBA
#undef  CONFIG_USER_SAMBA_SMBD
#undef  CONFIG_USER_SAMBA_NMBD
#undef  CONFIG_USER_SAMBA_SMBMOUNT
#undef  CONFIG_USER_SAMBA_SMBUMOUNT
#undef  CONFIG_USER_CTORRENT
#undef  CONFIG_USER_MC
#define CONFIG_USER_INETD_INETD 1
#define CONFIG_USER_IPROUTE2 1
#undef  CONFIG_USER_IPROUTE2_TC_TC
#undef  CONFIG_USER_IPROUTE2_IP_IFCFG
#undef  CONFIG_USER_IPROUTE2_IP_IP
#undef  CONFIG_USER_IPROUTE2_IP_ROUTEF
#undef  CONFIG_USER_IPROUTE2_IP_ROUTEL
#undef  CONFIG_USER_IPROUTE2_IP_RTACCT
#undef  CONFIG_USER_IPROUTE2_IP_RTMON
#undef  CONFIG_USER_IPROUTE2_IP_RTPR
#define CONFIG_USER_IPTABLES_IPTABLES 1
#define CONFIG_BRIDGE_NF_EBTABLES 1
#undef  CONFIG_USER_ROUTE_NETSTAT
#undef  CONFIG_USER_ROUTE_MIITOOL
#undef  CONFIG_USER_OPENSSL_APPS
#undef  CONFIG_USER_PARENTAL_CONTROL
#undef  CONFIG_USER_REMOTE_MANAGEMENT
#undef  CONFIG_USER_ROUTE_ROUTE
#define CONFIG_USER_ROUTED_ROUTED 1
#define CONFIG_USER_SNMPD_SNMPD_V2CTRAP 1
#undef  CONFIG_USER_TCPDUMP_WEB
#undef  CONFIG_USER_TCPDUMP_TCPDUMP
#define CONFIG_USER_TELNETD_TELNETD 1
#undef  CONFIG_USER_TFTPD_TFTPD
#define CONFIG_USER_MINIUPNPD 1
#define CONFIG_USE_SHARED_LIB 1
#define CONFIG_USER_MINI_UPNPD 1
#define CONFIG_USER_VSNTP 1

/*
 * Wireless-tools
 */
#undef  CONFIG_USER_WIRELESS_TOOLS

/*
 * Miscellaneous Applications
 */
#undef  CONFIG_USER_CHAT_CHAT
#undef  CONFIG_USER_PERL_PERL
#undef  CONFIG_USER_PYTHON_PYTHON
#undef  CONFIG_USER_SETSERIAL_SETSERIAL
#undef  CONFIG_USER_USBMOUNT_USBMOUNT

/*
 * USB tools
 */
#undef  CONFIG_USER_USBTOOLS

/*
 * LIRC
 */
#undef  CONFIG_USER_LIRC
#undef  CONFIG_USER_LIRC_LIRCD
#undef  CONFIG_USER_LIRC_IRRECORD
#undef  CONFIG_USER_LIRC_LIRCMD
#undef  CONFIG_USER_LIRC_IREXEC
#undef  CONFIG_USER_LIRC_IRW
#undef  CONFIG_USER_LIRC_MODE2

/*
 * BusyBox
 */
#define CONFIG_USER_BUSYBOX_BUSYBOX 1

/*
 * Applets
 */
#undef  CONFIG_USER_BUSYBOX_ADJTIMEX
#undef  CONFIG_USER_BUSYBOX_TIME
#define CONFIG_USER_BUSYBOX_ASH 1
#define CONFIG_USER_BUSYBOX_ASH_JOB_CONTROL 1
#undef  CONFIG_USER_BUSYBOX_AR
#undef  CONFIG_USER_BUSYBOX_BASENAME
#define CONFIG_USER_BUSYBOX_CAT 1
#undef  CONFIG_USER_BUSYBOX_CHGRP
#undef  CONFIG_USER_BUSYBOX_CHMOD
#undef  CONFIG_USER_BUSYBOX_CHOWN
#undef  CONFIG_USER_BUSYBOX_CHROOT
#define CONFIG_USER_BUSYBOX_CLEAR 1
#undef  CONFIG_USER_BUSYBOX_CMP
#define CONFIG_USER_BUSYBOX_CP 1
#undef  CONFIG_USER_BUSYBOX_CUT
#define CONFIG_USER_BUSYBOX_DATE 1
#undef  CONFIG_USER_BUSYBOX_DC
#undef  CONFIG_USER_BUSYBOX_DD
#define CONFIG_USER_BUSYBOX_DF 1
#undef  CONFIG_USER_BUSYBOX_DIRNAME
#define CONFIG_USER_BUSYBOX_DMESG 1
#undef  CONFIG_USER_BUSYBOX_DUTMP
#undef  CONFIG_USER_BUSYBOX_DU
#define CONFIG_USER_BUSYBOX_ECHO 1
#undef  CONFIG_USER_BUSYBOX_ENV
#define CONFIG_USER_BUSYBOX_EXPR 1
#undef  CONFIG_USER_BUSYBOX_FIND
#define CONFIG_USER_BUSYBOX_FREE 1
#undef  CONFIG_USER_BUSYBOX_FREERAMDISK
#undef  CONFIG_USER_BUSYBOX_FSCK_MINIX
#undef  CONFIG_USER_BUSYBOX_GETOPT
#define CONFIG_USER_BUSYBOX_GREP 1
#define CONFIG_USER_BUSYBOX_GREP_CONTEXT 1
#undef  CONFIG_USER_BUSYBOX_GREP_EGREP_ALIAS
#undef  CONFIG_USER_BUSYBOX_GUNZIP
#undef  CONFIG_USER_BUSYBOX_GZIP
#undef  CONFIG_USER_BUSYBOX_HALT
#undef  CONFIG_USER_BUSYBOX_HEAD
#define CONFIG_USER_BUSYBOX_HOSTNAME 1
#undef  CONFIG_USER_BUSYBOX_ID
#define CONFIG_USER_BUSYBOX_IFCONFIG 1
#define CONFIG_USER_BUSYBOX_IFCONFIG_STATUS 1
#undef  CONFIG_USER_BUSYBOX_IFCONFIG_SLIP
#define CONFIG_USER_BUSYBOX_IFCONFIG_HW 1
#undef  CONFIG_USER_BUSYBOX_IFCONFIG_MEMSTART_IOADDR_IRQ
#undef  CONFIG_USER_BUSYBOX_INIT
#undef  CONFIG_USER_BUSYBOX_INSMOD
#define CONFIG_USER_BUSYBOX_KILL 1
#define CONFIG_USER_BUSYBOX_KILLALL 1
#undef  CONFIG_USER_BUSYBOX_KLOGD
#undef  CONFIG_USER_BUSYBOX_LENGTH
#undef  CONFIG_USER_BUSYBOX_LN
#undef  CONFIG_USER_BUSYBOX_LOGGER
#undef  CONFIG_USER_BUSYBOX_LOGNAME
#define CONFIG_USER_BUSYBOX_LS 1
#define CONFIG_USER_BUSYBOX_LS_COLOR 1
#undef  CONFIG_USER_BUSYBOX_LS_USERNAME
#undef  CONFIG_USER_BUSYBOX_LS_TIMESTAMPS
#define CONFIG_USER_BUSYBOX_LS_FILETYPES 1
#define CONFIG_USER_BUSYBOX_LS_SORTFILES 1
#define CONFIG_USER_BUSYBOX_LS_RECURSIVE 1
#define CONFIG_USER_BUSYBOX_LS_FOLLOWLINKS 1
#undef  CONFIG_USER_BUSYBOX_LSMOD
#undef  CONFIG_USER_BUSYBOX_MAKEDEVS
#undef  CONFIG_USER_BUSYBOX_MD5SUM
#define CONFIG_USER_BUSYBOX_MKDIR 1
#undef  CONFIG_USER_BUSYBOX_MKFS_MINIX
#undef  CONFIG_USER_BUSYBOX_MKNOD
#undef  CONFIG_USER_BUSYBOX_MKTEMP
#undef  CONFIG_USER_BUSYBOX_MODPROBE
#undef  CONFIG_USER_BUSYBOX_MORE
#undef  CONFIG_USER_BUSYBOX_USE_TERMIOS
#define CONFIG_USER_BUSYBOX_MOUNT 1
#undef  CONFIG_USER_BUSYBOX_MOUNT_LOOP
#undef  CONFIG_USER_BUSYBOX_MTAB_SUPPORT
#undef  CONFIG_USER_BUSYBOX_NFSMOUNT
#define CONFIG_USER_BUSYBOX_MV 1
#undef  CONFIG_USER_BUSYBOX_NC
#define CONFIG_USER_BUSYBOX_NSLOOKUP 1
#undef  CONFIG_USER_BUSYBOX_PIDOF
#define CONFIG_USER_BUSYBOX_PING 1
#define CONFIG_USER_BUSYBOX_FANCY_PING 1
#undef  CONFIG_USER_BUSYBOX_PIVOT_ROOT
#undef  CONFIG_USER_BUSYBOX_POWEROFF
#undef  CONFIG_USER_BUSYBOX_PRINTF
#define CONFIG_USER_BUSYBOX_PS 1
#define CONFIG_USER_BUSYBOX_PWD 1
#undef  CONFIG_USER_BUSYBOX_RDATE
#undef  CONFIG_USER_BUSYBOX_READLINK
#define CONFIG_USER_BUSYBOX_REBOOT 1
#undef  CONFIG_USER_BUSYBOX_RENICE
#undef  CONFIG_USER_BUSYBOX_RESET
#define CONFIG_USER_BUSYBOX_RM 1
#undef  CONFIG_USER_BUSYBOX_RMDIR
#undef  CONFIG_USER_BUSYBOX_RMMOD
#define CONFIG_USER_BUSYBOX_ROUTE 1
#define CONFIG_USER_BUSYBOX_NETSTAT 1
#undef  CONFIG_USER_BUSYBOX_RPM2CPIO
#undef  CONFIG_USER_BUSYBOX_SED
#define CONFIG_USER_BUSYBOX_SHELL 1
#define CONFIG_USER_BUSYBOX_ASH 1
#define CONFIG_USER_BUSYBOX_SH_IS_ASH 1
#undef  CONFIG_USER_BUSYBOX_HUSH
#undef  CONFIG_USER_BUSYBOX_SH_IS_HUSH
#undef  CONFIG_USER_BUSYBOX_LASH
#undef  CONFIG_USER_BUSYBOX_SH_IS_LASH
#undef  CONFIG_USER_BUSYBOX_MSH
#undef  CONFIG_USER_BUSYBOX_SH_IS_MSH
#undef  CONFIG_USER_BUSYBOX_COMMAND_EDITING
#undef  CONFIG_USER_BUSYBOX_TAB_COMPLETION
#undef  CONFIG_USER_BUSYBOX_USERNAME_COMPLETION
#undef  CONFIG_USER_BUSYBOX_SH_STANDALONE_SHELL
#undef  CONFIG_USER_BUSYBOX_SH_FANCY_PROMPT
#undef  CONFIG_USER_BUSYBOX_SLEEP
#undef  CONFIG_USER_BUSYBOX_SORT
#undef  CONFIG_USER_BUSYBOX_STTY
#undef  CONFIG_USER_BUSYBOX_SYNC
#undef  CONFIG_USER_BUSYBOX_SYSLOGD
#define CONFIG_USER_BUSYBOX_TAIL 1
#undef  CONFIG_USER_BUSYBOX_FANCY_TAIL
#undef  CONFIG_USER_BUSYBOX_TAR
#undef  CONFIG_USER_BUSYBOX_TEE
#undef  CONFIG_USER_BUSYBOX_TELNET
#undef  CONFIG_USER_BUSYBOX_TEST
#undef  CONFIG_USER_BUSYBOX_TFTP
#define CONFIG_USER_BUSYBOX_TOP 1
#undef  CONFIG_USER_BUSYBOX_TOUCH
#undef  CONFIG_USER_BUSYBOX_TR
#define CONFIG_USER_BUSYBOX_TRACEROUTE 1
#undef  CONFIG_USER_BUSYBOX_TRUE_FALSE
#undef  CONFIG_USER_BUSYBOX_TTY
#undef  CONFIG_USER_BUSYBOX_UMOUNT
#undef  CONFIG_USER_BUSYBOX_UNAME
#undef  CONFIG_USER_BUSYBOX_UNIQ
#undef  CONFIG_USER_BUSYBOX_UNIX2DOS
#define CONFIG_USER_BUSYBOX_UPTIME 1
#undef  CONFIG_USER_BUSYBOX_USLEEP
#undef  CONFIG_USER_BUSYBOX_UUDECODE
#undef  CONFIG_USER_BUSYBOX_UUENCODE
#undef  CONFIG_USER_BUSYBOX_VI
#undef  CONFIG_USER_BUSYBOX_WATCHDOG
#undef  CONFIG_USER_BUSYBOX_WC
#undef  CONFIG_USER_BUSYBOX_WGET
#undef  CONFIG_USER_BUSYBOX_WHICH
#undef  CONFIG_USER_BUSYBOX_WHOAMI
#undef  CONFIG_USER_BUSYBOX_XARGS
#undef  CONFIG_USER_BUSYBOX_YES

/*
 * other features
 */
#undef  CONFIG_USER_BUSYBOX_VERBOSE_USAGE
#define CONFIG_USER_BUSYBOX_AUTOWIDTH 1
#undef  CONFIG_USER_BUSYBOX_NEW_MODULE_INTERFACE
#undef  CONFIG_USER_BUSYBOX_OLD_MODULE_INTERFACE
#undef  CONFIG_USER_BUSYBOX_INSMOD_VERSION_CHECKING
#define CONFIG_USER_BUSYBOX_HUMAN_READABLE 1

/*
 * RTK VoIP User applications
 */
#undef  CONFIG_USER_RTK_VOIP

/*
 * Debug Builds
 */
#undef  CONFIG_LIB_DEBUG
#undef  CONFIG_USER_DEBUG

/*
 * Debug libraries
 */
#undef  CONFIG_LIB_LIBCCMALLOC
#define CONFIG_VENDOR "Realtek"
#define CONFIG_PRODUCT "RTL8670"
#define CONFIG_LINUXDIR "linux-2.4.x"
#define CONFIG_LIBCDIR "uClibc"
#define CONFIG_LANGUAGE "ru_RU.UTF-8:ru"
#define VENDORS_AUTOCONF_INCLUDED
#undef AUTOCONF_INCLUDED
