#ifndef __CODEC_DEF_H__
#define __CODEC_DEF_H__

#include "rtk_voip.h"

enum START_CODEC_TYPE 
{
	CODEC_TYPE_G711, 
#ifdef CONFIG_RTK_VOIP_G7231
	CODEC_TYPE_G7231, 
#endif
#ifdef CONFIG_RTK_VOIP_G729AB
	CODEC_TYPE_G729,
#endif
#ifdef CONFIG_RTK_VOIP_G726
	CODEC_TYPE_G726,
#endif
#ifdef CONFIG_RTK_VOIP_GSMFR
	CODEC_TYPE_GSMFR,
#endif
#ifdef CONFIG_RTK_VOIP_T38
	CODEC_TYPE_T38,
#endif
	CODEC_TYPE_UNKNOW,
	CODEC_TYPE_NUMBER = CODEC_TYPE_UNKNOW,
};

// what kind of coding algorism
typedef enum
{
    DSPCODEC_ALGORITHM_G711U,
    DSPCODEC_ALGORITHM_G711A,
#ifdef CONFIG_RTK_VOIP_G7231
    DSPCODEC_ALGORITHM_G7231A53,
    DSPCODEC_ALGORITHM_G7231A63,
#endif
#ifdef CONFIG_RTK_VOIP_G729AB
    DSPCODEC_ALGORITHM_G729,
#endif
#ifdef CONFIG_RTK_VOIP_G726
    DSPCODEC_ALGORITHM_G72616,
    DSPCODEC_ALGORITHM_G72624,
    DSPCODEC_ALGORITHM_G72632,
    DSPCODEC_ALGORITHM_G72640,
#endif
#ifdef CONFIG_RTK_VOIP_GSMFR
	DSPCODEC_ALGORITHM_GSMFR,
#endif
#ifdef CONFIG_RTK_VOIP_T38
	DSPCODEC_ALGORITHM_T38,
#endif
    DSPCODEC_ALGORITHM_UNKNOW,
    DSPCODEC_ALGORITHM_NUMBER = DSPCODEC_ALGORITHM_UNKNOW,
} DSPCODEC_ALGORITHM;

enum CODEC_STATE
{
	INVALID,
	ENCODE,
	DECODE,
	BOTH
};

#endif /* __CODEC_DEF_H__ */

