#ifndef  WEB_LANGUAGE_DEFS_H
#define WEB_LANGUAGE_DEFS_H
#include "LINUX/options.h"
#ifdef EMBED
#include <linux/config.h>
#else
#include "../../../uClibc/include/linux/autoconf.h"
#endif





#if defined(ZTE_531B_BRIDGE_SC) || defined(ZTE_GENERAL_ROUTER_SC)
/*define chinese lang*/
#define Tfast_config	"快速设定"
#define Tfc_intro     "此快速设定将一步一步的指引你完成DSL设定."
#define Tattention    "注意:"
#define Tatt_intro    "完成快速设定后将会取代原先的设定."
#define Tint_conn_conf  "因特网连结设定——ATM PVC 设定"
#define Tint_conn_intro "请指定DSL连线所使用的虚拟路径编号（VPI）及虚拟通道编号（VCI）.请勿任意指定或更改它，\
除非ISP指定需进行此项更改."
#define Tnext_step    "下一步 >"
#define Tint_conn_type  "因特网连接设定——连线方式"
#define Tconn_type_intro  "请选择ISP所提供的广域网的连接方式."
#define Tconn_type    "广域网连接方式:"
#define Tencap_type   "数据封装模式:"
#define Tenter_vpi	"请输入VPI (0~255)!"
#define Tinvalid_vpi	"无效的VPI!"
#define Tenter_vci	"请输入VCI (0~65535)!"
#define Tinvalid_vci	"无效的VCI!"
#define Tget_chain_err	"获取链表记录出错!\n"
#define Tconn_exist	"连接已存在，是否删除已有连接?"
#define Tvc_exceed	"VC 数目超出最多限制!"
#define Tadd_err		"加入链表出错!"
#define Tsecond_ip_err	"设置第二个IP地址出错!"
#define Tsecond_mask_err	"设置第二局域网子网掩码时出错!"
#define Tdhcp_err		"设置DHCP 模式出错!"
#define Tget_ip_err		"获取IP地址出错!"
#define Tget_mask_err	"获取子网掩码出错!"
#define Tdhcp_range_err	"无效的DHCP 客户端地址范围!"
#define Tset_start_ip_err		"设置DHCP 客户端起始地址出错!"
#define Tset_end_ip_err		"设置DHCP 客户端结束地址出错!"
#define Tset_lease_err		"设置DHCP 租约时间出错!"
#define Tset_ip_err		"设置IP 地址出错!"
#define Tset_mask_err	"设置子网掩码出错!"
#define Tinvalid_ip		"无效的IP 地址!"
#define Tinvalid_mask	"无效的子网掩码!"
#define Tinvalid_ip2		"第二组IP 地址无效!"
#define Tinvalid_mask2	"第二组局域网子网掩码无效!"
#define Tip2vsip		"第一组 IP 地址和第二组 IP 地址必须属于不同的子网。"
#define Tinvalid_start_ip	"DHCP 客户端起始地址无效!"
#define Tinvalid_end_ip	"DHCP 客户端结束地址无效!"
#define Tinvalid_dhcp_ip	"DHCP 地址范围错误"
#define Tuser_long		"错误! 用户名太长."
#define Tpassw_long	"错误! 密码太长."
#define Tinvalid_ppp_type	"无效的PPP类型!"
#define Tconn_forever	", 永远在线"
#define Tconn_on_dem	", 自动拨号连线及断线，空闲时间 %d分钟"
#define Tconn_manual	", 手动连线"
#define Tdd_hh_mm		"%d天 %d时 %d分"
#define Tdhcp_ip_range	"DHCP IP 范围"
#define Tdhcp_lease_t	"DHCP 租约时间"
#define Tnapt			"网络地址转换(NAT)"
#define Twan_ip		"广域网 IP 地址"
#define Tres_gw		"预设网关"
#define Tauto_assign	"自动指定"
#define Tno_wan_ip		"无"
#define Tdnss			"DNS 服务器"
#define Tbytes			"字节"
#define Tping_recv		"%d 字节 来自 %s: icmp_seq=%u"
#define Tping_stat		"--- ping 诊断 ---"
#define Ttrans_pkt		"发送 %ld 个报文, "
#define Trecv_pkt		"接收 %ld 个报文."
#define Tno_conn		"连接不存在!"
#define Trecv_cell_suc	"Loopback 信元接收成功 !"
#define Trecv_cell_fail	"Loopback 失败 !"
#define Tadsl_diag_suc	"ADSL 诊断成功!!"
#define Tadsl_diag_fail	"ADSL 诊断失败!!"
#define Tdownstream	"下 行"
#define Tupstream		"上 行"
#define Tloop_annu		"环路衰减"
#define Tsig_annu		"信号衰减"
#define Thlin_scale		"Hlin 尺度"
#define Tsnr_marg		"信噪比裕度"
#define Tattain_rate		"可达速率"
#define Tout_power		"输出功率"
#define Ttone_num		"载波编号"
#define Tlan_conn_chk	"局域网连接检验"
#define Ttest_eth_conn	"测试以太网连接"
#define Ttest_adsl_syn	"测试 ADSL 同步"
#define Ttest_oam_f5_seg	"测试 ATM OAM F5 段 loopback"
#define Ttest_oam_f5_end	"测试 ATM OAM F5 端到端 loopback"
#define Ttest_oam_f4_seg	"测试 ATM OAM F4 段 loopback"
#define Ttest_oam_f4_end	"测试 ATM OAM F4 端到端 loopback"
#define Tadsl_conn_chk	"ADSL 连接检验"
#define Tint_conn_chk	"因特网连接检验"
#define Ttest_ppps_conn	"测试 PPP 服务器连接"
#define Ttest_auth		"测试 ISP 认证"
#define Ttest_assigned_ip	"测试分配的 IP 地址"
#define Tping_pri_dnss	"ping 首选的域名服务器"
#define Tback			"  返回  "
#define Tping_def_gw	"Ping 默认网关"
#define Tadsl_diag_wait	"测试结果会在3分钟后显示, 页面将会自动刷新. 请等待..."
#define Tppp_conn_excd	"PPPoE 连接数超出最大限制"
#define Tdef_gw_exist	"默认网关已经存在!"
#define Tinvalid_wan_dhcp	"无效的广域网 DHCP 值!"
#define Tinvalid_gw		"无效的预设网关值!"
#define Tinvalid_dns_mode	"无效的 DNS 模式!"
#define Tinvalid_dns	"DNS 地址无效!"
#define Treboot_wd0		"系统正在重启..."
#define Treboot_wd1		"DSL 桥已经正确配置并且正在重启..."
#define Treboot_wd2		"关闭桥配置窗口后请等待两分钟再打开 WEB 浏览器，"\
						"如果 DSL 桥的 LAN 口和 PC 的以太网口不在同一网段，请配置 PC 的"\
						"IP 地址以与 DSL 桥处于同一网段!"
#define Ttime_zone1		"系统时间被成功修改."
#define Ttime_zone2		"请刷新你的\"状态\"页."
#define Tset_tz			"设置时区出错!"
#define Tset_date_err	"无法设置日期"
#define Tset_ntp_ena	"设置 ntp 使能标志出错"
#define Tset_ntp_svr	"设置 ntp 服务器出错!"
#define Tset_ntp_ip		"设置 ntp 服务器 IP 地址出错!"
#define Tbrg_not_exist	"br0 接口不存在!"
#define Tyes			"是"
#define Tno				"否"
#define Tport_err		"端口设置出错!"
#define Twan_port		"广域网端口设置出错!"
#define Tsvr_port		"服务器端口设置出错!"
#define Tvrtsrv_rule	"执行虚拟服务器规则时出错!\n"
#define Tdmz_error		"无效的IP地址，应该在当前子网内!"

//for tcpiplan
#define strWrongIP "无效的IP地址值!"
#define strSetIPerror "设置IP地址错误!"
#define strWrongMask "无效的子网掩码值!"
#define strSetMaskerror "设置子网掩码错误!"

//for dhcp server
#define strGetDhcpModeerror "读取DHCP模式错误!"
#define strGetIperror "读取IP地址错误!"
#define strGetMaskerror "读取子网掩码错误!"
#define strInvalidRange "无效的DHCP客户端范围!"
#define strSetStarIperror "设置DHCP地址池初始地址错误!"
#define strSetEndIperror "设置DHCP地址池结束地址错误!"
#define strSetLeaseTimeerror "设置DHCP租约时间错误!"
#define strSetDomainNameerror "设置DHCP域名错误!"
#define strInvalidGatewayerror "无效的DHCP服务器网关地址!"
#define strSetGatewayerror "设置DHCP服务器网关地址错误!"
#define strSetDhcpModeerror "设置DHCP模式错误!"
#ifdef IP_BASED_CLIENT_TYPE
#define strInvalidRangepc "无效的PC地址池范围!"
#define strInvalidRangecmr "无效的摄像头地址池范围!"
#define strInvalidRangestb "无效的机顶盒地址池范围!"
#define strInvalidRangephn "无效的电话机地址池范围!"
#define strInvalidTypeRange "设备地址池不应在DHCP地址池之外!"
#define strOverlapRange "设备地址池不应重叠!"

#define strSetPcStartIperror "设置PC地址池初始地址错误!"
#define strSetPcEndIperror "设置PC地址池结束地址错误!"
#define strSetCmrStartIperror "设置摄像头地址池初始地址错误!"
#define strSetCmrEndIperror "设置摄像头地址池结束地址错误!"
#define strSetStbStartIperror "设置机顶盒地址池初始地址错误!"
#define strSetStbEndIperror "设置机顶盒地址池结束地址错误!"
#define strSetPhnStartIperror "设置电话机地址池初始地址错误!"
#define strSetPhnEndIperror "设置电话机地址池结束地址错误!"
#endif

#define strDelChainerror "删除链表记录错误!"
#define strModChainerror "修改链表记录错误!"

#define strInvalDhcpsAddress "无效的DHCP代理服务器地址值!"
#define strSetDhcpserror "设置DHCPS错误!"

#define strStaticipexist "该静态IP配置已经存在!"

//for wan set
#define strConnectExist "该连接已经存在!"
#define strMaxVc "错误：虚通道数目达到最大!"
#define strAddChainerror "添加链表记录错误!"


#define strUserNametoolong "错误!用户名长度多长。"
#define strUserNameempty "错误!用户名不能为空。"
#define strPasstoolong "错误!密码长度过长。"
#define strPassempty "错误!密码不能为空。"
#define strInvalPPPType "无效的PPP类型值!"
#define strDrouteExist "默认路由已经存在!"
#define strACName "错误!AC名称长度太长!"
#define strServerName "错误!服务名称长度太长!"
#define strInvalDHCP "无效的WAN端DHCP值!"
#define strInvalIP "无效的IP地址值!"
#define strIPAddresserror "错误!IP地址不能为空!"
#define strInvalGateway "无效的网关IP值!"
#define strGatewayIpempty "错误!网关IP值不能为空!"
#define strInvalMask "无效的子网掩码值!"
#define strMaskempty "子网掩码值不能为空!"
#define strMruErr	"无效的MRU值!"

#define strMaxNumPPPoE "已达到最大数目的PPPoE连接!"


//for atm set
#define strSelectvc "请选择一个虚通道!"
#define strGetChainerror "读取链表记录错误!\n"
#define strInvalidQos "无效的QoS!"
#define strInvalidPCR "无效的PCR!"
#define strInvalidCDVT "无效的CDVT!"
#define strInvalidSCR "无效的SCR!"

#define strInvalidMBS "无效的MBS!"

//for snmp
#define strSetcommunityROerror "设置snmpCommunityRO错误!"
#define strSetcommunityRWerror "设置snmpCommunityRW错误!"
#define strInvalTrapIp "无效的Trap Ip值!"
#define strSetTrapIperror "设置snmpTrapIpAddr错误!"


//for adsl set
#define strGetToneerror "读取ADSL载波数据错误!"
#define  WARNING_EMPTY_OLD_PASSWORD  "错误:旧密码不能为空 !."
#define  WARNING_EMPTY_NEW_PASSWORD  "错误:新密码不能为空 !."
#define WARNING_EMPTY_CONFIRMED_PASSWORD  "错误:确认密码不能为空 !."
#define WARNING_UNMATCHED_PASSWORD  "错误:新密码与确认密码必须一致!"
#define WARNING_GET_PASSWORD  "错误:读取密码错误!"
#define WARNING_SET_PASSWORD  "错误:密码修改失败!"
#define WARNING_WRONG_PASSWORD  "错误:密码错误!"
#define WARNING_WRONG_USER  "错误:用户名错误!"
#ifdef DEMOBOARD_1_1_2
#define ZTESOFTWAREVERSION "ZXDSL 831IIV1.0.0a_E27"
#else
#ifdef ZTE_531B_BRIDGE_SC
#define ZTESOFTWAREVERSION "ZXDSL 531BIIV1.0.0a_Z22"
#elif defined(ZTE_GENERAL_ROUTER_SC)
#define ZTESOFTWAREVERSION "ZXDSL 531BIIV1.0.1a-002"
#endif
#endif
#define COMMIT_REBOOT_TITLE    "保存配置并重启"
#define COMMIT_REBOOT_INFO "保存所做的所有修改并重新启动Modem !"
#define COMMIT_REBOOT_BUTTON  "<input type=\"submit\" value=\"确定\" name=\"save\" onclick=\"return saveClick()\">"

#define SYSTEM_LOG_TITLE "系统日志"
#define SYSTEM_LOG_BODY ""


//for wireless setting
#define   strDisbWlanErr				"禁用无线网络出错!"
#define   strInvdTxPower			"无效的发射功率值!"
#define   strSetMIBTXPOWErr		"设置 MIB_TX_POWER 出错!"
#define   strInvdMode				"无效的模式值!"
#define   strSetWPAWarn			"您不可以设置客户端模式为WPA-RADIUS!<br><br>请在安全设置网页中修改加密方法."
#define   strSetWEPWarn			"您不可以设置客户端模式为WEP-802.1x!<br><br>请在安全设置网页中修改加密方法."
#define   strSetMIBWLANMODEErr		"设置 MIB_WLAN_MODE 出错!" 
#define   strSetSSIDErr				"设置 SSID 出错!" 
#define   strInvdChanNum			"无效信道号!"           
#define   strSetChanErr				"设置信道出错!" 
#define   strInvdNetType			"无效网络类型值!" 
#define   strSetMIBWLANTYPEErr		"设置 MIB_WLAN_NETWORK_TYPE 失败!"
#define   strInvdAuthType			"无效的认证类型值!"
#define   strSetAuthTypeErr			"设置认证类型出错!"
#define   strSetAdapRateErr			"设置自适应速率失败!"
#define   strSetFixdRateErr			"设置固定速率失败!"
#define   strSetBaseRateErr			"设置基本发送速率失败!"
#define   strSetOperRateErr			"设置可操作发送速率失败!"
#define   strInvdTxRate				"无效的发送速率值!"
#define   strInvdBrodSSID			"无效的广播SSID设置值!"
#define   strSetBrodSSIDErr			"设置广播SSID出错!"
#define   strInvdProtection  			"无效的保护类型! "           //add by yq_zhou 2.10
#define   strInvdAggregation 			"无效的聚合设置"
#define   strInvdShortGI0 			"无效的保护区间! "
#define   strSetProtectionErr			"设置保护出错! "
#define   strSetAggregationErr 		"设置聚合出错! "
#define   strSetShortGI0Err			"设置保护区间出错! "
#define   strSetChanWidthErr  		"设置频道带宽出错! "
#define   strSetCtlBandErr 			"设置控制边带出错! "
#define   strSetBandErr				"设置频段出错!"
#define   strEnabAccCtlErr			"启用接入控制功能出错!"
#define   strInvdMACAddr			"无效的MAC地址!"
#define   strAddAcErrForFull			"添加出错，接入控制表已满!"
#define   strMACInList				"该MAC地址已在列表中!"
#define   strAddListErr				"添加链表出错!"
#define   strDelListErr				"删除链表出错!"
#define   strFragThreshold			"无效的分段极限值!"
#define   strSetFragThreErr			"设置分段极限值失败!"
#define   strRTSThreshold			"无效的RTS极限值!"
#define   strSetRTSThreErr			"设置RTS极限值出错!"
#define   strInvdBeaconIntv			"无效的Beacon间隔值!"
#define   strSetBeaconIntvErr		"设置Beacon间隔出错!"
#define   strInvdPreamble			"无效的前导码值"
#define   strSetPreambleErr			"设置前导码失败!"
#define   strInvdDTIMPerd			"无效的DTIM周期!"
#define   strSetDTIMErr				"设置DTIM周期失败!"
#define   strInvdIAPP				"无效的IAPP值."
#define   strMIBIAPPDISBErr			"设置MIB_WLAN_IAPP_DISABLED失败!"
#define   strSetRelayBlockErr			"关闭中继失败!"
#define   strSetLanWlanBlokErr		"设置LAN/WLAN阻塞失败!"
#define   strSetWlanWMMErr			"设置无线WMM(QoS)失败!"
#define   strMACAddr				"MAC地址"
#define   strSelect					"选择"
#define   strGetMBSSIBTBLErr		"获取MIB_MBSSIB_TBL出错!"
#define   strGetVAPMBSSIBTBLErr		"获取虚拟SSID MIB_MBSSIB_TBL出错!"
#define   strNotSuptSSIDType		"出错!不支持该SSID"
#define   strNoSSIDTypeErr			"出错，未选择SSID"
#define   strNoEncryptionErr			"出错！未选择加密方法"
#define   strInvdEncryptErr			"无效的加密方法"
#define   strSetWLANENCRYPTErr		"设置MIB_WLAN_ENCRYPT出错!"
#define   strSet8021xWarning		"出错！802.1x认证方法只可以用在AP模式下"
#define   strSet1xEnabErr			"启用802.1x认证出错!"
#define   strGetWLANWEPErr			"获取MIB_WLAN_WEP出错!"
#define   strSetWLANWEPErr			"设置MIB_WLAN_WEP出错!"
#define   strSetWPARADIUSWarn		"出错! WPA-RADIUS认证方法只可以用在AP模式下."
#define   strInvdWPAAuthValue		"出错，无效的WPA认证值!"
#define   strSetAUTHTYPEErr			"设置MIB_WLAN_AUTH_TYPE出错!"
#define   strNoPSKFormat			"出错！未选择预共享密钥格式"
#define   strInvdPSKFormat			"出错!无效的预共享密钥格式"
#define   strSetWPAPSKFMATErr		"设置MIB_WLAN_WPA_PSK_FORMAT出错!"
#define   strInvdPSKValue			"出错！无效的预共享密钥"
#define   strSetWPAPSKErr			"设置MIB_WLAN_WPA_PSK出错！"
#define   strInvdRekeyDay			"出错！无效的日期值."
#define   strInvdRekeyHr			"出错！无效的时值."
#define   strInvdRekeyMin			"出错！无效的分值."
#define   strInvdRekeySec			"出错！无效的秒值."
#define   strSetREKEYTIMEErr		"设置MIB_WLAN_WPA_GROUP_REKEY_TIME出错!"
#define   strInvdRSPortNum			"出错！无效的端口号"
#define   strSetRSPortErr			"设置RADIUS服务器端口号出错!"
#define   strNoIPAddr				"未输入IP地址!"
#define   strInvdRSIPValue			"无效的RADIUS服务器IP地址!"
#define   strSetIPAddrErr			"设置RADIUS服务器IP地址出错!"
#define   strRSPwdTooLong			"密码太长!"
#define   strSetRSPwdErr			"设置RADIUS服务器密码出错!"
#define   strInvdRSRetry			"无效的RADIUS服务器重试值!"
#define   strSetRSRETRYErr			"设置MIB_WLAN_RS_RETRY出错!"
#define   strInvdRSTime				"无效的RADIUS时间值!"
#define   strSetRSINTVLTIMEErr		"设置MIB_WLAN_RS_INTERVAL_TIME出错!"
#define   strInvdWepKeyLen			"出错!无效的WEP密码长度值."
#define   strSetMIBWLANWEPErr		"设置MIB_WLAN_WEP失败！"
#define   strGetMBSSIBTBLUpdtErr	"获取MIB_MBSSIB_TBL出错(更新的)."
#define   strGetMBSSIBWEPTBLErr	"获取MIB_MBSSIB_WEP_TBL出错！"
#define   strKeyLenMustExist			"必须设置密钥长度!"
#define   strInvdKeyLen				"无效的密钥长度值!"
#define   strKeyTypeMustExist		"必须设置密钥格式!"
#define   strInvdKeyType			"无效的密钥格式!"
#define   strSetWepKeyTypeErr		"设置密钥格式出错!"
#define   strInvdDeftKey				"无效的默认密钥!"
#define   strSetDeftKeyErr			"设置默认密钥出错!"
#define   strInvdKey1Len			"加密密钥1长度不对!"
#define   strInvdWEPKey1			"无效的WEP加密密钥1!"
#define   strSetWEPKey1Err			"设置WEP加密密钥1出错!"
#define   strInvdKey2Len			"加密密钥2长度不对!"
#define   strInvdWEPKey2			"无效的WEP加密密钥2!"
#define   strSetWEPKey2Err			"设置WEP加密密钥2出错!"
#define   strInvdKey3Len			"加密密钥3长度不对!"
#define   strInvdWEPKey3			"无效的WEP加密密钥3!"
#define   strSetWEPKey3Err			"设置WEP加密密钥3出错!"
#define   strInvdKey4Len			"加密密钥4长度不对!"
#define   strInvdWEPKey4			"无效的WEP加密密钥4!"
#define   strSetWEPKey4Err			"设置WEP加密密钥4出错!"
#define   strGetMBSSIBWEPTLBUpdtErr   "获取MIB_MBSSIB_WEP_TBL 出错(更新的)!"
#define   strWdsComment			"注释"
#define   strSetEnableErr   			"设置启用标志出错!"
#define   strCommentTooLong 		"错误! 注释太长."
#define   strGetEntryNumErr 			"获取表项数量出错!" 
#define   strErrForTablFull 			"列表已满，不能再增加新的表项!" 
#define   strAddEntryErr    			"增加表项出错!"
#define   strDelRecordErr   			"删除链表项出错!"
#define   strModifyAcltblErr			"修改接入控制列表出错，在禁用状态下不能修改列表!"


#define   strInvdDomain				"无效的国家/地区值!"
#define   strSetCOUNTRYAREAErr		"设置 国家/地区 出错!"
#define   strSetREGDOMAINErr		"设置REG_DOMAIN出错!"

#define   strDefault					"默认"
#define   strUSA					"美国"
#define   strCHINA					"中国"
#define   strHONGKONG				"中国香港"
#define   strMACAO					"中国澳门"
#define   strTAIWAN				"中国台湾省"
#define   strJAPAN					"日本"
#define   strEUROPE				"欧洲"
#define   strANTIGUA_BARBUDA 		"安提瓜和巴布达"
#define   strARGENTINA    			 "阿根廷"
#define   strARUBA         				 "阿鲁巴岛"
#define   strAUSTRALIA  			 "澳大利亚"
#define   strAUSTRIA       			 "奥地利"
#define   strBAHAMAS       			 "巴哈马群岛"
#define   strBANGLADESH   			 "孟加拉国"
 #define  strBARBADOS    			"巴巴多斯岛"
 #define  strBELGIUM    				 "比利时" 
 #define  strBERMUDA    				 "百慕大群岛"
 #define  strBOLIVIA     				"玻利维亚"
 #define  strBOSNIA_HERZEGOVINA 	"波斯尼亚-黑塞哥维那" 
 #define  strBRAZIL      				"巴西"
 #define  strBULGARIA    			"保加利亚"
 #define  strCANADA      				"加拿大"
 #define  strCAYMAN_ISLANDS  		"开曼群岛" 
 #define  strCHILE       				"智利"
 #define  strCOLOMBIA    			"哥伦比亚"
 #define  strCOSTA_RICA  			"哥斯达黎加"
 #define  strCROATIA     				"克罗地亚"
 #define  strCYPRUS      				"塞浦路斯"
 #define  strCZECH_REPUBLIC  		"捷克"
 #define  strDENMARK      			"丹麦" 
 #define  strDOMINICAN_REPUBLIC  	"多米尼加共和国"
 #define  strECUADOR     			"厄瓜多尔"
 #define  strEGYPT       				"埃及"
 #define  strEL_SALVADOR			 "萨尔瓦多" 
 #define  strESTONIA     				"爱沙尼亚"
 #define  strFINLAND     				"芬兰"
 #define  strFRANCE      				"法国"
 #define  strGERMANY     			"德国"
 #define  strGREECE      				"希腊"
 #define  strGUAM        				"关岛"
 #define  strGUATEMALA   			"危地马拉"
 #define  strHAITI      				 "海地"
 #define  strHONDURAS   			 "洪都拉斯"
 #define  strHUNGARY     			"匈牙利"
 #define  strICELAND     				"冰岛"
 #define  strINDIA       				"印度"
 #define  strINDONESIA   			"印度尼西亚"
 #define  strIRELAND     				"爱尔兰"
 #define  strISRAEL      				"以色列"
 #define  strITALY       				"意大利"
 #define  strJORDAN     				 "约旦"
 #define  strKOREA       				"韩国" 
 #define  strLATVIA      				"拉脱维亚"
 #define  strLIECHTENSTEIN   		"列支敦士登"
 #define  strLITHUANIA   			"立陶宛"
 #define  strLUXEMBOURG  			"卢森堡"
 #define  strMALAYSIA   				"马来群岛"
 #define  strMALTA       				"马耳他"
 #define  strMEXICO      				"墨西哥"
 #define  strMONACO      				"摩纳哥"
 #define  strNETHERLANDS 			"荷兰"
 #define  strNETHERLANDS_ANTILLES  "荷兰-安的列斯群岛"
 #define  strNEW_ZEALAND 			"新西兰"
 #define  strNICARAGUA   			"尼加拉瓜"
 #define  strNIGERIA     				"尼日利亚"
 #define  strNORWAY      			"挪威"
 #define  strPAKISTAN    			"巴基斯坦"
 #define  strPANAMA      				"巴拿马"
 #define  strPARAGUAY    			"巴拉圭"
 #define  strPERU        				"秘鲁"
 #define  strPHILIPPINES 			"菲律宾"
 #define  strPOLAND      				"波兰"
 #define  strPORTUGAL    			"葡萄牙"
 #define  strROMANIA     			"罗马尼亚"
 #define  strRUSSIAN_FEDERATION  	"俄罗斯联邦"
 #define  strSAUDI_ARABIA  			"沙特阿拉伯"
 #define  strSINGAPORE   			"新加坡"
 #define  strSLOVAKIA    			"斯洛伐克"
 #define  strSLOVENIA    			"斯洛文尼亚"
 #define  strSOUTH_AFRICA  			"南非"
 #define  strSPAIN       				"西班牙"
 #define  strSWEDEN      				"瑞典"
 #define  strSWITZERLAND 			"瑞士"
 #define  strTANZANIA 				"坦桑尼亚" 
 #define  strTHAILAND    			"泰国"
 #define  strTUNISIA     				"突尼斯"
 #define  strTURKEY      				"土耳其"
 #define  strUKRAINE     				"乌克兰"
 #define  strUNITED_ARAB_EMIRATES  "阿联酋"
 #define  strUNITED_KINGDOM  		"(大不列颠)联合王国"
 #define  strURUGUAY     			"乌拉圭"
 #define  strVENEZUELA   			"委内瑞拉"
 #define  strVIET_NAM     			"越南"



#define  INFO_ENABLED  	"开启"
#define  INFO_DISABLED 	"禁用"

//for web upgrade
#define   FILEOPENFAILED "文件打开错误!"
#define   FILEWITHWRONGSIG	"电子签名不对，升级不成功！！！"

//for tr069
#ifdef _CWMP_MIB_
#define strSetCerPasserror  "设置CPE证书密码错误!"
#define strACSURLWrong  "ACS的URL不能为空!"
#define strSSLWrong "CPE不支持SSL!URL不能以'https://'开始!"
#define strSetACSURLerror "设置ACS的URL错误!"
#define strSetUserNameerror "设置用户名错误!"
#define strSetPasserror "设置密码错误!"
#define strSetInformEnableerror "设置Inform消息使能错误!"
#define strSetInformIntererror "设置Inform消息时间间隔错误!"
#define strSetConReqUsererror "设置请求连接用户名错误!"
#define strSetConReqPasserror "设置请求连接密码错误!"
#define strSetCWMPFlagerror "设置CWMP_FLAG错误!"
#define strGetCWMPFlagerror "读取CWMP_FLAG错误!"
#define strUploaderror "上传错误!"
#define strMallocFail "分配内存失败!"
#define strArgerror "参数不足\n"
#endif

//for dns web fmdns.c
#define Tinvalid_DNS_mode "DNS 模式设定错误"
#define TDNS_mib_get_error      "获取DNS MIB错误!"
#define Tinvalid_DNS_address  	"非法的DNS服务器地址!"
#define TDNS_mib_set_error		"设定DNS MIB错误!"


//for ipqos  fmqos.c
#define Texceed_max_rules				"您设定的规则太多了!"
#define Tinvalid_source_ip     "源IP错误."
#define Tinvalid_source_netmask 			"源子网掩码错误."
#define Tinvalid_source_port 				"源端口错误."
#ifdef QOS_SPEED_LIMIT_SUPPORT
#define Tinvalid_pvc_bandwidth				"pvc带宽有错."
#endif
#define Tinvalid_destination_ip			"目的IP错误."
#define Tinvalid_destination_netmask		"目的子网掩码错误."
#define Tinvalid_destination_port			"目的端口错误."
#define Tinvalid_speed  					"速度错误 "
#define Tadd_chain_error					"添加失败."
#define Tdelete_chain_error				"删除失败."
#define Tinvalid_if_ip			"接口IP地址无效!"
#define Tinvalid_if_mask		"接口mask地址无效!"


//for firewall ip/port filter, fmfwall.c

#define Tprotocol_empty							"协议类型不能为空."
#define Tinvalid_port_range							"端口范围有误"
#define Tinvalid_rule_action						"处理方式有误"
#define Tinvalid_source_mac						"源MAC地址非法."
#define Tinvalid_dest_mac						"目的MAC地址非法."
#define Toutgoing_ippfilter   						"上行"
#define Tincoming_ippfilter						"下行"
#define Tdeny_ippfilter							"拒绝通过"
#define Tallow_ippfilter							"允许通过"
//for dos
#define strSetDosSYSSYNFLOODErr   "设置 DoS SYSSYN_FLOOD 出错!"
#define strSetDosSYSFINFLOODErr   "设置 DoS SYSFIN_FLOOD 出错!" 
#define strSetDosSYSUDPFLOODErr   "设置 DoS SYSUDP_FLOOD 出错!" 
#define strSetDosSYSICMPFLOODErr  "设置 DoS SYSICMP_FLOOD 出错!"
#define strSetDosPIPSYNFLOODErr   "设置 DoS PIPSYN_FLOOD 出错!"
#define strSetDosPIPFINFLOODErr   "设置 DoS PIPFIN_FLOOD 出错!"
#define strSetDosPIPUDPFLOODErr   "设置 DoS PIPUDP_FLOOD 出错!"
#define strSetDosPIPICMPFLOODErr  "设置 DoS PIPICMP_FLOOD 出错!"
#define strSetDosIPBlockTimeErr   "设置 DoS IP Block Timer 出错!"
#define strSetDosEnableErr        "设置 DoS enable 出错!"
#define strSetOkToCommitReboot   "修改成功，如果要生效，请保存配置并重启系统!"

//for wan config(static pppoe IP)
#define Tip_addr		"IP地址"
#define Tdynamic_ip		"自动获取IP"
#define Tstatic_ip		"用户指定IP"

#define Tinvalid_ip_net		"无效的IP地址，应该在当前局域网子网内!\n"

//for url blocking 
#define TstrUrlExist        "该域名已存在!"
#define TstrKeyExist       "该关键词已存在!"
#define TMaxUrl             "域名记录已达最大条数!"
#define TMaxKey           "关键词记录已达最大条数!"

//for acl
#define strIpExist   "该IP地址已经存在!"
#define strMacExist	 "该MAC地址已经存在!"
#define strSetInterfaceerror   "设置ACL接口错误!"
#define strSetACLCAPerror  "设置ACL使能错误!"
#define strWrongRange "设置IP地址范围错误，起始地址应小于结束地址!"
#define strWrongRangeDifflan  "设置IP地址范围错误，两地址应在同一网段!"

//nat session
#define strSetNatSessionError	"设置NAT会话限制使能出错!"

#else
#define Tfast_config	"Fast Configure"
#define Tfc_intro     "the fast configuration will help you finish the configuration step by step."
#define Tattention    "attention:"
#define Tatt_intro    "original configuration will be replaced by the fast configuration."
#define Tint_conn_conf  "Internet Connection Configure -- ATM PVC config"
#define Tint_conn_intro "please set VPI and VCI. Do not modify it, unless ISP need modify it."
#define Tnext_step    "next step >"
#define Tint_conn_type  "Internet Connection Configure -- connection type"
#define Tconn_type_intro    "please select WAN connection type provided by ISP."
#define Tconn_type    "WAN connection type:"
#define Tencap_type   "encapsulation:"
#define Tenter_vpi	"please Enter VPI (0~255)"
#define Tinvalid_vpi	"invalid VPI!"
#define Tenter_vci	"please enter VCI (0~65535)"
#define Tinvalid_vci	"invalid VCI!"
#define Tget_chain_err	"Get chain record error!\n"
#define Tconn_exist	"Connection already exists, delete existed connection?"
#define Tvc_exceed	"Error: Maximum number of VC exceeds !"
#define Tadd_err		"Error! Add chain record."
#define Tsecond_ip_err		"Set second IP-address error!"
#define Tsecond_mask_err	"Set second subnet-mask error!"
#define Tdhcp_err			"Set dhcp mode MIB error!"
#define Tget_ip_err		"Get IP-address error!"
#define Tget_mask_err	"Get Subnet Mask error!"
#define Tdhcp_range_err	"Invalid DHCP client range!"
#define Tset_start_ip_err		"Set DHCP client start range error!"
#define Tset_end_ip_err		"Set DHCP client end range error!"
#define Tset_lease_err		"Set DHCP lease time error!"
#define Tset_ip_err		"Set IP-address error!"
#define Tset_mask_err	"Set net mask error!"
#define Tinvalid_ip		"Invalid IP-address value!"
#define Tinvalid_mask	"Invalid subnet-mask value!"
#define Tinvalid_ip2		"Invalid second IP-address value!"
#define Tinvalid_mask2	"Invalid second subnet-mask value!"
#define Tip2vsip		"first Lan and second Lan must belong to different subNet!"
#define Tinvalid_start_ip	"Invalid DHCP start IP-address value!"
#define Tinvalid_end_ip	"Invalid DHCP end IP-address value!"
#define Tinvalid_dhcp_ip	"DHCP address range error!"
#define Tuser_long		"Error! User Name length too long."
#define Tpassw_long	"Error! Password length too long."
#define Tinvalid_ppp_type	"Invalid PPP type value!"
#define Tconn_forever	", connect forever"
#define Tconn_on_dem	", connect on demand, idle for %d minute"
#define Tconn_manual	", connect manually"
#define Tdd_hh_mm		"%dday %dhour %dmin"
#define Tdhcp_ip_range	"DHCP IP Range"
#define Tdhcp_lease_t	"DHCP Lease Time"
#define Tnapt			"NAPT"
#define Twan_ip		"WAN IP"
#define Tres_gw		"Reserved Gateway"
#define Tauto_assign	"auto assigned"
#define Tno_wan_ip		"none"
#define Tdnss			"DNS Server"
#define Tbytes			"data bytes"
#define Tping_recv		"%d bytes from %s: icmp_seq=%u"
#define Tping_stat		"--- ping statistics ---"
#define Ttrans_pkt		"%ld packets transmitted, "
#define Trecv_pkt		"%ld packets received."
#define Tno_conn		"Connection not exists!"
#define Trecv_cell_suc	"Loopback cell received successfully !"
#define Trecv_cell_fail	"Loopback failed !"
#define Tadsl_diag_suc	"ADSL Diagnostics successful !!"
#define Tadsl_diag_fail	"ADSL Diagnostics failed !!"
#define Tdownstream	"Downstream"
#define Tupstream		" Upstream "
#define Tloop_annu		"Loop Attenuation"
#define Tsig_annu		"Signal Attenuation"
#define Thlin_scale		"Hlin Scale"
#define Tsnr_marg		"SNR Margin"
#define Tattain_rate		"Attainable Rate"
#define Tout_power		"Output Power"
#define Ttone_num		"Tone Number"
#define Tlan_conn_chk	"LAN Connection Check"
#define Ttest_eth_conn	"Test Ethernet LAN Connection"
#define Ttest_adsl_syn	"Test ADSL Synchronization"
#define Ttest_oam_f5_seg	"Test ATM OAM F5 Segment Loopback"
#define Ttest_oam_f5_end 	"Test ATM OAM F5 End-to-end Loopback"
#define Ttest_oam_f4_seg	"Test ATM OAM F4 Segment Loopback"
#define Ttest_oam_f4_end	"Test ATM OAM F4 End-to-end Loopback"
#define Tadsl_conn_chk	"ADSL Connection Check"
#define Tint_conn_chk 	"Internet Connection Check"
#define Ttest_ppps_conn	"Test PPP Server Connection"
#define Ttest_auth		"Test Authentication with ISP"
#define Ttest_assigned_ip	"Test the assigned IP Address"
#define Tping_pri_dnss	"Ping Primary Domain Name Server"
#define Tback			"  Back  "
#define Tping_def_gw	"Ping Default Gateway"
#define Tadsl_diag_wait	"The test result will come out 3 minutes later and the page will refresh itself automatically. Please wait ...\n"
#define Tppp_conn_excd	"Maximum number of PPPoE connections exceeds in this vc!"
#define Tdef_gw_exist	"Default route already exists !"
#define Tinvalid_wan_dhcp	"Invalid WAN DHCP value!"
#define Tinvalid_gw		"Invalid reserved gateway IP-address value!"
#define Tinvalid_dns_mode	"Invalid DNS mode value!"
#define Tinvalid_dns	"Invalid DNS address!"
#define Treboot_wd0		"The System is Restarting ..."
#define Treboot_wd1		"The DSL bridge has been configured and is rebooting."
#define Treboot_wd2		"Close the DSL Router Configuration window and wait"\
			" for 2 minutes before reopening your web browser."\
			" If necessary, reconfigure your PC's IP address to match"\
			" your new configuration.";
#define Ttime_zone1		"System Date has been modified successfully."
#define Ttime_zone2		"Please reflesh your \"Status\" page."
#define Tset_tz			"set time zone error!"
#define Tset_date_err	"cannot set date"
#define Tset_ntp_ena	"Set enabled flag error!"
#define Tset_ntp_svr	"Set NTP server error!"
#define Tset_ntp_ip		"Set NTP server IP error!"
#define Tbrg_not_exist	"br0 interface not exists !!"
#define Tyes			"yes"
#define Tno				"no"
#define Tport_err		"port size error!"
#define Twan_port		"wan port set error!"
#define Tsvr_port		"server port set error!"
#define Tvrtsrv_rule	"execute virtual server rules failed!\n"
#define Tdmz_error		"Invalid IP address! It should be set within the current subnet."

#define strWrongIP "Invalid IP-address value!"
#define strSetIPerror "Set IP-address error!"
#define strWrongMask "Invalid subnet-mask value!"
#define strSetMaskerror "Set subnet-mask error!"

#define strGetDhcpModeerror "Get DHCP MIB error!"
#define strGetIperror "Get IP-address error!"
#define strGetMaskerror "Get Subnet Mask error!"
#define strInvalidRange "Invalid DHCP client range!"
#define strSetStarIperror "Set DHCP client start range error!"
#define strSetEndIperror "Set DHCP client end range error!"
#define strSetLeaseTimeerror "Set DHCP lease time error!"
#define strSetDomainNameerror "Set DHCP Domain Name error!"
#define strInvalidGatewayerror "Invalid DHCP Server Gateway Address value!"
#define strSetGatewayerror "Set DHCP Server Gateway Address error!"
#define strSetDhcpModeerror "Set DHCP error!"

#define strDelChainerror "Delete chain record error!"
#define strModChainerror "Modify chain record error!"

#define strInvalDhcpsAddress "Invalid DHCPS address value!"
#define strSetDhcpserror "Set DHCPS MIB error!"

#define strStaticipexist "This static ip configuration already exists!"

#define strConnectExist "Connection already exists!"
#define strMaxVc "Error: Maximum number of VC exceeds !"
#define strAddChainerror "Error! Add chain record."
#define strTableFull "Error! Table Full."

#define strUserNametoolong "Error! User Name length too long."
#define strUserNameempty "Error! User Name cannot be empty."
#define strPasstoolong "Error! Password length too long."
#define strPassempty "Error! Password cannot be empty."
#define strInvalPPPType "Invalid PPP type value!"
#define strDrouteExist  "Default route already exists !"
#define strACName "Error! AC-Name length too long."
#define strServerName "Error! Service-Name length too long."

#define strInvalDHCP "Invalid WAN DHCP value!"
#define strInvalIP "Invalid IP-address value!"
#define strIPAddresserror "Error! IP address cannot be empty."
#define strInvalGateway "Invalid remote IP-address value!"
#define strGatewayIpempty "Error! Remote IP address cannot be empty."
#define strInvalMask "Invalid subnet mask value!"
#define strMaskempty "Error! Subnet mask cannot be empty."
#define strMruErr	"Invalid MTU!"

#define strMaxNumPPPoE "Maximum number of PPPoE connections exceeds in this vc!"



#define strSelectvc "Please select one vc!"
#define strGetChainerror "Get chain record error!\n"
#define strInvalidQos "Invalid QoS!"
#define strInvalidPCR "Invalid PCR!"
#define strInvalidCDVT "Invalid CDVT!"
#define strInvalidSCR "Invalid SCR!"
#define strInvalidMBS "Invalid MBS!"

#define strSetcommunityROerror "Set snmpCommunityRO mib error!"
#define strSetcommunityRWerror "Set snmpCommunityRW mib error!"
#define strInvalTrapIp "Invalid Trap IP value!"
#define strSetTrapIperror "Set snmpTrapIpAddr mib error!"


#define strGetToneerror "ERROR: Get ADSL Tone MIB error!"
#define  WARNING_EMPTY_OLD_PASSWORD  "ERROR: Old Password cannot be empty."
#define  WARNING_EMPTY_NEW_PASSWORD  "ERROR: New Password cannot be empty."
#define WARNING_EMPTY_CONFIRMED_PASSWORD  "ERROR: Confirmed Password cannot be empty."
#define WARNING_UNMATCHED_PASSWORD  "ERROR: New Password is not the same as Confirmed Password."
#define WARNING_GET_PASSWORD  "ERROR,Get password failed!"
#define WARNING_SET_PASSWORD  "ERROR: Modify password failed!"
#define WARNING_WRONG_PASSWORD  "ERROR: wrong password!"
#define WARNING_WRONG_USER  "ERROR: wrong username!"


#define COMMIT_REBOOT_TITLE    "Commit and Reboot"
#define COMMIT_REBOOT_INFO " This page is used to commit changes to system memory and reboot your system."
#define COMMIT_REBOOT_BUTTON  "<input type=\"submit\" value=\"Commit and Reboot\" name=\"save\" onclick=\"return saveClick()\">"

#define SYSTEM_LOG_TITLE "System Log"

//for wireless setting
#define   strDisbWlanErr				"Set disabled flag error!"
#define   strInvdTxPower			"Invalid TxPower value!"
#define   strSetMIBTXPOWErr		"Set MIB_TX_POWER error!"
#define   strInvdMode				"Invalid mode value!"
#define   strSetWPAWarn			"You cannot set client mode with WPA-RADIUS!<br><br>Please change the encryption method in security page first."
#define   strSetWEPWarn			"You cannot set client mode with WEP-802.1x!<br><br>Please change the encryption method in security page first."
#define   strSetMIBWLANMODEErr		"Set MIB_WLAN_MODE error!"
#define   strSetSSIDErr				"Set SSID error!"
#define   strInvdChanNum			"Invalid channel number!" 
#define   strSetChanErr				"Set channel number error!"
#define   strInvdNetType			"Invalid network type value!"
#define   strSetMIBWLANTYPEErr		"Set MIB_WLAN_NETWORK_TYPE failed!"
#define   strInvdAuthType			"Error! Invalid authentication value."
#define   strSetAuthTypeErr			"Set authentication failed!"
#define   strSetAdapRateErr			"Set rate adaptive failed!"
#define   strSetFixdRateErr			"Set fix rate failed!"
#define   strSetBaseRateErr			"Set Tx basic rate failed!"
#define   strSetOperRateErr			"Set Tx operation rate failed!"
#define   strInvdTxRate				"invalud value of tx rate!"
#define   strInvdBrodSSID			"Error! Invalid hiddenSSID value."
#define   strSetBrodSSIDErr			"Set hidden ssid failed!"
#define   strInvdProtection             	"Invalid protection setting "      //add by yq_zhou 2.10
#define   strInvdAggregation	                "Invalid aggregation setting"
#define   strInvdShortGI0 	                "Invalid short GI setting"
#define   strSetProtectionErr          	"Set protection  error"
#define   strSetAggregationErr	  	"Set aggregation  error"
#define   strSetShortGI0Err			"Set guard interval error"
#define   strSetChanWidthErr  		"Set channel width error"
#define   strSetCtlBandErr 			"Set control sideband error"
#define   strSetBandErr				"Set band error!"
#define   strEnabAccCtlErr			"Set enabled access control error!"
#define   strInvdMACAddr			"Error! Invalid MAC address."
#define   strAddAcErrForFull			"Cannot add new entry because table is full!"
#define   strMACInList				"Entry already exists!"
#define   strAddListErr				"Error! Add chain record."
#define   strDelListErr				"Delete chain record error!"
#define   strFragThreshold			"Error! Invalid value of fragment threshold."
#define   strSetFragThreErr			"Set fragment threshold failed!"
#define   strRTSThreshold			"Error! Invalid value of RTS threshold."
#define   strSetRTSThreErr			"Set RTS threshold failed!"
#define   strInvdBeaconIntv			"Error! Invalid value of Beacon Interval."
#define   strSetBeaconIntvErr		"Set Beacon interval failed!"
#define   strInvdPreamble			"Error! Invalid Preamble value."
#define   strSetPreambleErr			"Set Preamble failed!"
#define   strInvdDTIMPerd			"Error! Invalid value of DTIM period."
#define   strSetDTIMErr				"Set DTIM period failed!"
#define   strInvdIAPP				"Error! Invalid IAPP value."
#define   strMIBIAPPDISBErr			"Set MIB_WLAN_IAPP_DISABLED failed!"
#define   strSetRelayBlockErr			"Set block relay failed!"
#define   strSetLanWlanBlokErr		"Set block ethernet to wireless failed!"
#define   strSetWlanWMMErr			"Set WMM(QoS) to wireless failed!"
#define   strMACAddr				"MAC Address"
#define   strSelect					"Select"
#define   strGetMBSSIBTBLErr		"Error! Get MIB_MBSSIB_TBL error."
#define   strGetVAPMBSSIBTBLErr		"Error! formWlanMBSSID: Get MIB_MBSSIB_TBL for VAP SSID error."
#define   strNotSuptSSIDType		"Error! Not support this SSID TYPE."
#define   strNoSSIDTypeErr			"Error! no SSID TYPE."
#define   strNoEncryptionErr			"Error! no encryption method."
#define   strInvdEncryptErr			"Invalid encryption method!"
#define   strSetWLANENCRYPTErr		"Set MIB_WLAN_ENCRYPT mib error!"
#define   strSet8021xWarning		"Error! 802.1x authentication cannot be used when device is set to client mode."
#define   strSet1xEnabErr			"Set 1x enable flag error!"
#define   strGetWLANWEPErr			"Get MIB_WLAN_WEP MIB error!"
#define   strSetWLANWEPErr			"Set WEP MIB error!"
#define   strSetWPARADIUSWarn		"Error! WPA-RADIUS cannot be used when device is set to client mode."
#define   strInvdWPAAuthValue		"Error! Invalid wpa authentication value."
#define   strSetAUTHTYPEErr			"Set MIB_WLAN_AUTH_TYPE failed!"
#define   strNoPSKFormat			"Error! no psk format."
#define   strInvdPSKFormat			"Error! invalid psk format."
#define   strSetWPAPSKFMATErr		"Set MIB_WLAN_WPA_PSK_FORMAT failed!"
#define   strInvdPSKValue			"Error! invalid psk value."
#define   strSetWPAPSKErr			"Set MIB_WLAN_WPA_PSK error!"
#define   strInvdRekeyDay			"Error! Invalid value of rekey day."
#define   strInvdRekeyHr			"Error! Invalid value of rekey hr."
#define   strInvdRekeyMin			"Error! Invalid value of rekey min."
#define   strInvdRekeySec			"Error! Invalid value of rekey sec."
#define   strSetREKEYTIMEErr		"Set MIB_WLAN_WPA_GROUP_REKEY_TIME error!"
#define   strInvdRSPortNum			"Error! Invalid value of RS port number."
#define   strSetRSPortErr			"Set RS port error!"
#define   strNoIPAddr				"No RS IP address!"
#define   strInvdRSIPValue			"Invalid RS IP-address value!"
#define   strSetIPAddrErr			"Set RS IP-address error!"
#define   strRSPwdTooLong			"RS password length too long!"
#define   strSetRSPwdErr			"Set RS password error!"
#define   strInvdRSRetry			"Invalid RS retry value!"
#define   strSetRSRETRYErr			"Set MIB_WLAN_RS_RETRY error!"
#define   strInvdRSTime				"Invalid RS time value!"
#define   strSetRSINTVLTIMEErr		"Set MIB_WLAN_RS_INTERVAL_TIME error!"
#define   strInvdWepKeyLen			"Error! Invalid wepkeylen value."
#define   strSetMIBWLANWEPErr		"Set MIB_WLAN_WEP failed!"
#define   strGetMBSSIBTBLUpdtErr	"Error! Get MIB_MBSSIB_TBL error(Updated)."
#define   strGetMBSSIBWEPTBLErr	"Error! Get MIB_MBSSIB_WEP_TBL error."
#define   strKeyLenMustExist			"Key length must exist!"
#define   strInvdKeyLen				"Invalid key length value!"
#define   strKeyTypeMustExist		"Key type must exist!"
#define   strInvdKeyType			"Invalid key type value!"
#define   strSetWepKeyTypeErr		"Set WEP key type error!"
#define   strInvdDeftKey				"Invalid default tx key id!"
#define   strSetDeftKeyErr			"Set default tx key id error!"
#define   strInvdKey1Len			"Invalid key 1 length!"
#define   strInvdWEPKey1			"Invalid wep-key1 value!"
#define   strSetWEPKey1Err			"Set wep-key1 error!"
#define   strInvdKey2Len			"Invalid key 2 length!"
#define   strInvdWEPKey2			"Invalid wep-key2 value!"
#define   strSetWEPKey2Err			"Set wep-key2 error!"
#define   strInvdKey3Len			"Invalid key 3 length!"
#define   strInvdWEPKey3			"Invalid wep-key3 value!"
#define   strSetWEPKey3Err			"Set wep-key3 error!"
#define   strInvdKey4Len			"Invalid key 4 length!"
#define   strInvdWEPKey4			"Invalid wep-key4 value!"
#define   strSetWEPKey4Err			"Set wep-key4 error!"
#define   strGetMBSSIBWEPTLBUpdtErr   "Error! Get MIB_MBSSIB_WEP_TBL error(Updated)."
#define   strWdsComment			"Comment"
#define   strSetEnableErr   			"Set enabled flag error!"
#define   strCommentTooLong 		"Error! Comment length too long."
#define   strGetEntryNumErr 			"Get entry number error!" 
#define   strErrForTablFull 			"Cannot add new entry because table is full!" 
#define   strAddEntryErr    			"Add table entry error!"
#define   strDelRecordErr   			"Delete chain record error!"


//for web upgrade
#define   FILEOPENFAILED "File open error!"
#define   FILEWITHWRONGSIG	"Invalid signature!"

#define  INFO_ENABLED 	"Enabled"
#define  INFO_DISABLED	"Disabled"
//for tr069
#if defined(_CWMP_MIB_)

#define strSetCerPasserror  "Set CPE Certificat's Password error!"
#define strACSURLWrong  "ACS's URL can't be empty!"
#define strSSLWrong "CPE does not support SSL! URL should not start with 'https://'!"
#define strSetACSURLerror "Set ACS's URL error!"
#define strSetUserNameerror "Set User Name error!"
#define strSetPasserror "Set Password error!"
#define strSetInformEnableerror "Set Inform Enable error!"
#define strSetInformIntererror "Set Inform Interval error!"
#define strSetConReqUsererror "Set Connection Request UserName error!"
#define strSetConReqPasserror "Set Connection Request Password error!"
#define strSetCWMPFlagerror "Set CWMP_FLAG error!"
#define strGetCWMPFlagerror "Get CWMP_FLAG error!"
#define strUploaderror "Upload error!"
#define strMallocFail "malloc failure!"
#define strArgerror "Insufficient args\n"
#endif

//for dns web fmdns.c
#define Tinvalid_DNS_mode "Invalid DNS mode value!"
#define TDNS_mib_get_error      "Get DNS MIB error!"
#define Tinvalid_DNS_address  	"Invalid DNS address value!"
#define TDNS_mib_set_error		"Set DNS MIB error!"

//for ipqos  fmqos.c  ip/portfilter, fmfwall.
#define Texceed_max_rules				"Error: Maximum number of Qos rule exceeds !"	
#define Tinvalid_source_ip   				"Error! Source IP."
#define Tinvalid_source_netmask 			"Error! Source Netmask"
#define Tinvalid_source_port 				"Error! Invalid source port."
#ifdef QOS_SPEED_LIMIT_SUPPORT
#define Tinvalid_pvc_bandwidth				"Error! Invalid pvc  bandwidth."
#endif
#define Tinvalid_destination_ip			"Error! Destination IP."
#define Tinvalid_destination_netmask		"Error! Destination Netmask."
#define Tinvalid_destination_port			"Error! Invalid destination port."
#define Tinvalid_speed					"Error!Invalid speed"
#define Tadd_chain_error					"Error! Add chain record."
#define Tdelete_chain_error				"Error! Delete chain record."
#define Tinvalid_if_ip					"Error! invalid IP addr!"
#define Tinvalid_if_mask				"Error! invalid mask addr."


//for firewall ip/port filter, fmfwall.c

#define Tprotocol_empty							"Error! Protocol type cannot be empty."
#define Tinvalid_port_range							"Error! port range error"
#define Tinvalid_rule_action						"Invalid Rule Action value!"
#define Tinvalid_source_mac						"Error! Invalid src MAC address."
#define Tinvalid_dest_mac						"Error! Invalid dst MAC address."
#define Toutgoing_ippfilter   						"Outgoing"
#define Tincoming_ippfilter						"Incoming"
#define Tdeny_ippfilter							"Deny"
#define Tallow_ippfilter						"Allow"
#define Tinvalid_rule							"Invaild! This is a duplicate or conflicting rule !"

//for dos
#define strSetDosSYSSYNFLOODErr   "Set DoS SYSSYN_FLOOD error!"
#define strSetDosSYSFINFLOODErr   "Set DoS SYSFIN_FLOOD error!" 
#define strSetDosSYSUDPFLOODErr   "Set DoS SYSUDP_FLOOD error!" 
#define strSetDosSYSICMPFLOODErr  "Set DoS SYSICMP_FLOOD error!"
#define strSetDosPIPSYNFLOODErr   "Set DoS PIPSYN_FLOOD error!"
#define strSetDosPIPFINFLOODErr   "Set DoS PIPFIN_FLOOD error!"
#define strSetDosPIPUDPFLOODErr   "Set DoS PIPUDP_FLOOD error!"
#define strSetDosPIPICMPFLOODErr  "Set DoS PIPICMP_FLOOD error!"
#define strSetDosIPBlockTimeErr   "Set DoS IP Block Timer error!"
#define strSetDosEnableErr        "Set DoS enable error!"

//for wan config(static pppoe IP)
#define Tip_addr		"IP Address"
#define Tdynamic_ip		"Dynamic IP"
#define Tstatic_ip		"Static IP"

#define Tinvalid_ip_net		"Invalid IP address! It should be set within the current subnet.\n"

#define TstrUrlExist        " FQDN already exists!"
#define TstrKeyExist        " KEYword already exists!"
#define TMaxUrl             "Maximum number of FQDN records exceeds!"
#define TMaxKey             "Maximum number of KEYWORD records exceeds!" 


#define strIpExist   "The IP addr has been exist!"
#define strMacExist	 "The MAC addr has been exist!"
#define strSetInterfaceerror   "Set ACL's Interface error!"
#define strSetACLCAPerror  "Set ACL Capability error!"

#define strSetNatSessionError "Set Nat session limitation error!"

#endif

#endif
